#!/usr/bin/env node
/**
 * The README's worked pass, run.
 *
 * It used to be six lines someone typed, and one of them searched for a string the
 * frame does not contain. Now the block is generated from what the server actually
 * answers, and `src/docs.test.mjs` regenerates it and compares — so editing the README
 * by hand fails, and changing what the tools do fails until the README is regenerated.
 *
 *   node src/worked-pass.mjs           print the block
 *   node src/worked-pass.mjs --write   put it back into README.md
 */
import { spawn } from 'node:child_process';
import { existsSync, readFileSync, writeFileSync, rmSync } from 'node:fs';

export const START = '<!-- worked-pass: generated by src/worked-pass.mjs — do not edit by hand -->';
export const END = '<!-- /worked-pass -->';

const FILE = 'samples/kyowon-full.fig';
const LOGIN = '2063:280';
const GNB = '97:3081';
const LIBRARY = 'samples/matsq.fig';
const OUT = 'out/worked-pass';

function client() {
  const proc = spawn('node', [new URL('./mcp.mjs', import.meta.url).pathname], { stdio: ['pipe', 'pipe', 'inherit'] });
  const seen = [];
  let buf = '';
  proc.stdout.on('data', (d) => {
    buf += d;
    for (let i; (i = buf.indexOf('\n')) >= 0; ) {
      const line = buf.slice(0, i);
      buf = buf.slice(i + 1);
      if (line.trim()) seen.push(JSON.parse(line));
    }
  });
  let id = 0;
  const rpc = async (method, params) => {
    const n = ++id;
    proc.stdin.write(JSON.stringify({ jsonrpc: '2.0', id: n, method, params }) + '\n');
    for (let i = 0; i < 1200; i++) {
      const hit = seen.find((m) => m.id === n);
      if (hit) return hit.result;
      await new Promise((r) => setTimeout(r, 20));
    }
    throw new Error(`timeout waiting for ${method}`);
  };
  return { rpc, stop: () => proc.kill() };
}

const nodes = (n) => 1 + (Array.isArray(n.children) ? n.children.reduce((a, c) => a + nodes(c), 0) : 0);
const row = (call, said) => `${call.padEnd(46)} → ${said}`;

export async function workedPass() {
  const { rpc, stop } = client();
  await rpc('initialize', { protocolVersion: '2024-11-05', capabilities: {}, clientInfo: { name: 'worked-pass', version: '1' } });
  const call = async (name, args) => JSON.parse((await rpc('tools/call', { name, arguments: args })).content[0].text);
  try {
    const frames = await call('list_frames', { file: FILE });
    const login = frames.find((f) => f.id === LOGIN);
    const ir = await call('get_frame', { file: FILE, frame: LOGIN });
    const tokens = await call('get_tokens', { file: FILE, frame: LOGIN });
    rmSync(OUT, { recursive: true, force: true });
    const assets = await call('export_assets', { file: FILE, frame: LOGIN, outDir: OUT });
    const kinds = Object.values(assets).map((a) => a.file.split('.').pop());
    const found = await call('find_nodes', { file: LIBRARY, query: 'Products', frame: GNB });
    const first = found.matches[0];
    const picked = await call('get_frame', { file: LIBRARY, frame: GNB, select: first.id });

    return [
      '```',
      `# ${FILE}`,
      row('list_frames(file)', `${frames.length} frames; ${login.id} ${login.name} ${login.w}×${login.h}`),
      row(`get_frame(file, "${LOGIN}")`, `${nodes(ir)} nodes — the whole screen in one call`),
      row(`get_tokens(file, "${LOGIN}")`, `${tokens.colors.length} colours, ${tokens.text.length} text styles, named`),
      row(`export_assets(file, "${LOGIN}", "${OUT}")`,
        `${Object.keys(assets).length} files: ${[...new Set(kinds)].sort().map((k) => `.${k}`).join(' ')}`),
      '',
      `# ${LIBRARY} — a frame too big for one call`,
      row(`find_nodes(file, "Products", frame: "${GNB}")`,
        `${found.matches.length} matches; first ${first.id}`),
      row(`get_frame(file, "${GNB}", select: …)`, `${nodes(picked)} nodes, under ${first.path.join(' > ')}`),
      '```',
    ].join('\n');
  } finally {
    stop();
    rmSync(OUT, { recursive: true, force: true });
  }
}

if (import.meta.url === `file://${process.argv[1]}`) {
  if (!existsSync(FILE) || !existsSync(LIBRARY)) {
    console.log(`skip — ${existsSync(FILE) ? LIBRARY : FILE} not present`);
    process.exit(process.env.CI ? 1 : 0);
  }
  const block = await workedPass();
  if (!process.argv.includes('--write')) {
    console.log(block);
  } else {
    const readme = readFileSync('README.md', 'utf8');
    const before = readme.indexOf(START);
    const after = readme.indexOf(END);
    if (before < 0 || after < 0) throw new Error('README.md has no worked-pass markers');
    writeFileSync('README.md', `${readme.slice(0, before)}${START}\n${block}\n${readme.slice(after)}`);
    console.log('README.md updated');
  }
}
